import type { ProjectDetail, StoryboardScene } from "@creonome/contracts";

function timecode(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return `${String(minutes).padStart(2, "0")}:${String(remainder).padStart(2, "0")}`;
}

function detail(label: string, value: string | null): string | null {
  return value ? `**${label}:** ${value}` : null;
}

function sceneMarkdown(scene: StoryboardScene): string {
  const endSeconds = scene.startSeconds + (scene.durationSeconds ?? 0);
  const details = [
    detail("Shot", scene.shotType),
    detail("Voiceover", scene.voiceover),
    detail("On-screen text", scene.onScreenText),
    detail("B-roll", scene.bRoll),
    detail("Transition", scene.transition),
    detail("Required asset", scene.requiredAsset),
    detail("Sound", scene.sound),
    detail("Editing note", scene.editingNote),
    detail("Reference frame", scene.referenceFrameUrl),
  ].filter((value): value is string => Boolean(value));

  return [
    `### ${String(scene.position).padStart(2, "0")} · ${scene.heading} (${timecode(scene.startSeconds)}–${timecode(endSeconds)})`,
    "",
    scene.description,
    ...(details.length ? ["", ...details] : []),
  ].join("\n");
}

export function projectExportFileName(title: string): string {
  const slug = title
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 200);
  return `${slug || "creonome-project"}.md`;
}

export function buildProjectMarkdown(project: ProjectDetail): string {
  const sections = [
    `# ${project.title}`,
    "",
    `> Creonome project export · ${project.currentLevel} · version ${project.currentVersion}`,
    "",
    `- Platform: ${project.platform ?? "not specified"}`,
    `- Opportunity score: ${project.score ?? "not available"}`,
    `- Updated: ${project.updatedAt}`,
  ];

  if (project.script) {
    sections.push(
      "",
      "## Script",
      "",
      `- Estimated duration: ${project.script.durationSeconds ?? "—"} seconds`,
      `- Platforms: ${project.script.platforms.join(", ") || "not specified"}`,
      "",
      "### Hook",
      "",
      project.script.hook,
      "",
      "### Body",
      "",
      project.script.body,
    );
    if (project.script.callToAction) {
      sections.push("", "### Call to action", "", project.script.callToAction);
    }
    if (project.script.caption) {
      sections.push("", "### Caption", "", project.script.caption);
    }
  }

  if (project.storyboard) {
    sections.push(
      "",
      "## Storyboard",
      "",
      `- Aspect ratio: ${project.storyboard.aspectRatio}`,
      `- Total duration: ${project.storyboard.durationSeconds ?? "—"} seconds`,
      "",
      ...project.storyboard.scenes.flatMap((scene, index) => [
        sceneMarkdown(scene),
        ...(index < project.storyboard!.scenes.length - 1 ? [""] : []),
      ]),
    );
  }

  sections.push("", "---", "Generated by Creonome.", "");
  return sections.join("\n");
}
