import type {
  OpportunityBatch,
  OpportunityStrategy,
} from "@creonome/contracts";
import { demoOpportunities, type DemoOpportunity } from "./demo-opportunities";

type OpportunitySource = Pick<
  { getCurrentOpportunities(): Promise<OpportunityBatch> },
  "getCurrentOpportunities"
>;

const presentationByStrategy = Object.fromEntries(
  demoOpportunities.map(
    ({
      strategy,
      badge,
      duration,
      hook,
      why,
      reserve,
      verdict,
      effort,
      channel,
    }) => [
      strategy,
      { badge, duration, hook, why, reserve, verdict, effort, channel },
    ],
  ),
) as Record<
  OpportunityStrategy,
  Pick<
    DemoOpportunity,
    | "badge"
    | "duration"
    | "hook"
    | "why"
    | "reserve"
    | "verdict"
    | "effort"
    | "channel"
  >
>;

export function presentOpportunity(
  opportunity: OpportunityBatch["opportunities"][number],
): DemoOpportunity {
  return {
    ...opportunity,
    ...presentationByStrategy[opportunity.strategy],
  };
}

export async function loadTodayOpportunities(
  client: OpportunitySource,
): Promise<{
  source: "api" | "demo";
  /**
   * True when the API returned a real batch (source: "api") but that batch
   * was itself generated by the backend's local fallback path because the
   * structured AI generator failed -- see OpportunityBatchSchema.fallback.
   * Always false for the client-side "demo" fallback, which is a distinct,
   * already-disclosed situation (the `source === "demo"` banner).
   */
  fallback: boolean;
  generatedAt?: string;
  opportunities: DemoOpportunity[];
}> {
  try {
    const batch = await client.getCurrentOpportunities();
    return {
      source: "api",
      fallback: batch.fallback,
      generatedAt: batch.generatedAt,
      opportunities: batch.opportunities.map(presentOpportunity),
    };
  } catch {
    return { source: "demo", fallback: false, opportunities: demoOpportunities };
  }
}
